export const UPDATE_VIDEOS_LIST = 'UPDATE_VIDEOS_LIST';
export const UPDATE_VIDEOS_CURRENT = 'UPDATE_VIDEOS_CURRENT';
export const UPDATE_VIDEOS_FAIL = 'UPDATE_VIDEOS_FAIL';
export const UPDATE_VIDEOS_LOADING = 'UPDATE_VIDEOS_LOADING';
